### ISSUE TITLE
Caractère étrange avec Firefox

### ISSUE THREAD

**Issue by cborne** [cfdev/mchildhood#1]
Bonsoir, je viens de mettre le thème en place à cette adresse : https://cyrille-borne.com/prof/

j'ai un caractère bizarre qui apparaît à la fin du titre et ailleurs
![capture du 2016-11-03 20-50-37](https://cloud.githubusercontent.com/assets/3888577/19982697/5d321826-a207-11e6-83bf-ac0d06585fc4.png)

**Comment by cfdev** [comment]
Merci c'est corrigé ;)
