### ISSUE TITLE
Les caractères accentués n'apparaissent pas dans les titres

### ISSUE THREAD

**Issue by cborne** [cfdev/mchildhood#2]
Remontée d'un de mes lecteurs, on voit qu'effectivement il manque le "é" sur réparer. 

![capture du 2016-11-05 21-38-32](https://cloud.githubusercontent.com/assets/3888577/20033414/3ba25780-a3a0-11e6-94cc-b62ba578a965.png)

**Comment by cfdev** [comment]
Ok cela vient de la police de caractères je vais devoir en changer...

**Comment by cborne** [comment]
up :)

**Comment by cfdev** [comment]
J'avais zappé dsl ! C'est normalement corrigé Cyrille ;)
